#!/usr/bin/env bash
#
# NISAR LA/LB split-spectrum ionospheric correction.
#
# Method          : Split-spectrum method in Gomba et al. (2016)
# Developed by    : Yajun Zhang
# Updated by      : Xin Wang
# Affiliation     : University of Science and Technology of China (USTC)
#                   Hefei, China
# Final update    : 2026-08-01
#
# Processing method:
#   The LA/LB ionospheric inversion follows the split-spectrum method in
#   Gomba et al. (2016).
#   The raw correction is quality-masked with LA/LB coherence, filled with
#   nearest_grid_c_exact.py, then smoothed with median, boxcar, and Gaussian
#   spatial filters at a nominal 20 km scale.
#
# Input:
#   LA/intf/<pair>/unwrap.grd
#   LB/intf/<pair>/unwrap.grd
#
# Output:
#   iono_correction/
#
# Usage:
#   ./run7_nsr_iono_LA_LB.sh
#

set -euo pipefail

if [[ $# -ne 0 ]]; then
    echo "Usage: $(basename "$0")" >&2
    exit 1
fi

filter_wavelength="${IONO_FILTER_WAVELENGTH:-20000}"
if ! awk -v x="$filter_wavelength" \
    'BEGIN {exit !(x > 0 && x == int(x))}'; then
    echo "ERROR: IONO_FILTER_WAVELENGTH must be a positive integer in metres." >&2
    exit 1
fi

coherence_threshold="${IONO_CORR_THRESHOLD:-0.1}"
if ! awk -v x="$coherence_threshold" 'BEGIN {exit !(x >= 0 && x <= 1)}'; then
    echo "ERROR: IONO_CORR_THRESHOLD must be between zero and one." >&2
    exit 1
fi

# This reproduces the tested fast/stable path: direct reconstruction between
# robust iterations, followed by one surface reconstruction after the
# final Gaussian filter.
upsample_method="grdsample"

if ! command -v gmt >/dev/null 2>&1; then
    echo "ERROR: GMT is not available in PATH." >&2
    exit 1
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_dir="${NISAR_PROJECT_DIR:-$script_dir}"
project_dir="$(cd "$project_dir" && pwd)"
work_dir="${IONO_OUTPUT_DIR:-$project_dir/iono_correction}"
nearest_python="$script_dir/nearest_grid_c_exact.py"
python_cmd="${IONO_PYTHON:-python3}"

if [[ ! -f "$nearest_python" ]]; then
    echo "ERROR: nearest_grid_c_exact.py was not found:" >&2
    echo "       $nearest_python" >&2
    exit 1
fi
if ! "$python_cmd" -c 'import netCDF4, numpy, scipy' >/dev/null 2>&1; then
    if command -v python >/dev/null 2>&1 && \
       python -c 'import netCDF4, numpy, scipy' >/dev/null 2>&1; then
        python_cmd="python"
    else
        echo "ERROR: nearest_grid_c_exact.py requires Python netCDF4, NumPy and SciPy." >&2
        echo "       Activate the GMTSAR conda environment or set IONO_PYTHON." >&2
        exit 1
    fi
fi

if [[ ! -d "$project_dir/LA/intf" || ! -d "$project_dir/LB/intf" ]]; then
    echo "ERROR: Expected LA/intf and LB/intf below:" >&2
    echo "       $project_dir" >&2
    exit 1
fi

# Find exactly one common LA/LB interferogram containing unwrap.grd.
common_pairs=($(
    comm -12 \
        <(find "$project_dir/LA/intf" -type f -name "unwrap.grd" \
            -print | awk -F/ '{print $(NF-1)}' | sort -u) \
        <(find "$project_dir/LB/intf" -type f -name "unwrap.grd" \
            -print | awk -F/ '{print $(NF-1)}' | sort -u)
))

if [[ ${#common_pairs[@]} -eq 0 ]]; then
    echo "ERROR: No common LA/LB interferogram with unwrap.grd was found." >&2
    exit 1
fi

if [[ ${#common_pairs[@]} -gt 1 ]]; then
    echo "ERROR: More than one common LA/LB interferogram was found:" >&2
    printf '       %s\n' "${common_pairs[*]}" >&2
    exit 1
fi

pair_name="${common_pairs[0]}"
la_dir="$project_dir/LA/intf/$pair_name"
lb_dir="$project_dir/LB/intf/$pair_name"
unwrap_a_src="$la_dir/unwrap.grd"
unwrap_b_src="$lb_dir/unwrap.grd"
corr_a_src="$la_dir/corr.grd"
corr_b_src="$lb_dir/corr.grd"

if [[ ! -f "$corr_a_src" || ! -f "$corr_b_src" ]]; then
    echo "ERROR: Ionospheric quality filtering requires LA/LB corr.grd." >&2
    exit 1
fi

prm_a_list=($(
    find "$la_dir" -maxdepth 1 -type f -name 'NSR_*A.PRM' -print | sort
))
prm_b_list=($(
    find "$lb_dir" -maxdepth 1 -type f -name 'NSR_*B.PRM' -print | sort
))

if [[ ${#prm_a_list[@]} -eq 0 || ${#prm_b_list[@]} -eq 0 ]]; then
    echo "ERROR: Could not find NSR_*A.PRM and NSR_*B.PRM." >&2
    exit 1
fi

# Use the earlier acquisition PRM, matching the original run7 selection.
prm_a="${prm_a_list[0]}"
prm_b="${prm_b_list[0]}"

mkdir -p "$work_dir"
cd "$work_dir"

# Remove only files generated by this script.
rm -f \
    master_A.PRM master_B.PRM unwrap_A.grd unwrap_B.grd trans.dat \
    unwrap_A_onB_raw.grd unwrap_A_onB_metric.grd \
    unwrap_A_onB_metric_filt.grd unwrap_A_onB.grd \
    iono_correction.grd iono_correction_m.grd _prefill_raw.grd \
    trend_surface.grd residual.grd validmask.grd working_residual.grd \
    filt_residual.grd filtered_residual.grd \
    edge_distance.grd edge_taper_fraction.grd edge_taper_weight.grd \
    filtered_residual_edge_tapered.grd retrend_full_LB.grd \
    iono_full_LB.grd _iono_relabeled.grd iono_correction_filt.grd \
    _iono_cf_tmp.grd unwrap_corrected.grd unwrap_corrected_ll.grd \
    _edit_A.grd tmp1.grd tmp2.grd iono_correction_report.txt \
    corr_A_onB.grd corr_mean.grd corr_mask.grd outlier_mask.grd \
    iono_quality.grd iono_quality_m.grd quality_nan_mask.grd \
    filter_working.grd filter_stage.grd filter_coarse.grd filter_mixed.grd \
    iono_boxcar.grd iono_gaussian.grd iono_correction_filtered_LB_m.grd

ln -s "$prm_a" master_A.PRM
ln -s "$prm_b" master_B.PRM
ln -s "$unwrap_a_src" unwrap_A.grd
ln -s "$unwrap_b_src" unwrap_B.grd

freq_a="$(awk '$1 == "radar_wavelength" {
    print 299792458/$3; exit
}' master_A.PRM)"
freq_b="$(awk '$1 == "radar_wavelength" {
    print 299792458/$3; exit
}' master_B.PRM)"

if [[ -z "$freq_a" || -z "$freq_b" ]]; then
    echo "ERROR: Failed to read radar_wavelength from the PRMs." >&2
    exit 1
fi

if ! awk -v fa="$freq_a" -v fb="$freq_b" \
    'BEGIN {exit !(fb > fa)}'; then
    echo "ERROR: Expected f_B > f_A." >&2
    exit 1
fi

read -r a_xmin a_xmax a_ymin a_ymax a_xinc a_yinc < <(
    gmt grdinfo unwrap_A.grd -C |
        awk '{print $2, $3, $4, $5, $8, $9}'
)
read -r b_xmin b_xmax b_ymin b_ymax b_xinc b_yinc < <(
    gmt grdinfo unwrap_B.grd -C |
        awk '{print $2, $3, $4, $5, $8, $9}'
)

rng_samp_rate="$(awk '$1 == "rng_samp_rate" {print $3; exit}' master_B.PRM)"
sc_vel="$(awk '$1 == "SC_vel" {print $3; exit}' master_A.PRM)"
earth_radius="$(awk '$1 == "earth_radius" {print $3; exit}' master_A.PRM)"
sc_height="$(awk '$1 == "SC_height" {print $3; exit}' master_A.PRM)"
prf="$(awk '$1 == "PRF" {print $3; exit}' master_A.PRM)"

if [[ -z "$rng_samp_rate" || -z "$sc_vel" ||
      -z "$earth_radius" || -z "$sc_height" || -z "$prf" ]]; then
    echo "ERROR: Missing rng_samp_rate, SC_vel, earth_radius, SC_height, or PRF." >&2
    exit 1
fi

ground_velocity="$(awk -v v="$sc_vel" -v h="$sc_height" \
    -v r="$earth_radius" 'BEGIN {print v/sqrt(1+h/r)}')"
azimuth_res="$(awk -v v="$ground_velocity" -v p="$prf" \
    'BEGIN {print v/p}')"
range_res="$(awk -v s="$rng_samp_rate" \
    'BEGIN {print 299792458/(2*s)}')"

echo "============================================================"
echo "NISAR LA/LB IONOSPHERIC CORRECTION"
echo "Project directory : $project_dir"
echo "Pair              : $pair_name"
echo "Filter wavelength : $filter_wavelength m"
echo "Filter method     : median/boxcar/Gaussian spatial filtering"
echo "Coherence threshold: $coherence_threshold"
echo "Nearest fill      : nearest_grid_c_exact.py"
echo "Python interpreter: $python_cmd"
echo "Coarse-grid rebuild: $upsample_method"
echo "LA input          : $unwrap_a_src"
echo "LB input          : $unwrap_b_src"
echo "Output directory  : $work_dir"
echo "============================================================"
echo "Frequencies       : f_A=$freq_a Hz, f_B=$freq_b Hz"
echo "LA grid           : x=[$a_xmin,$a_xmax], y=[$a_ymin,$a_ymax]"
echo "LA increments     : $a_xinc, $a_yinc"
echo "LB grid           : x=[$b_xmin,$b_xmax], y=[$b_ymin,$b_ymax]"
echo "LB increments     : $b_xinc, $b_yinc"
echo "LB metric spacing : range=$range_res m, azimuth=$azimuth_res m"

# ---------------------------------------------------------------------------
# 1. Relabel LA to the complete LB extent and downsample.
# ---------------------------------------------------------------------------

prefilter_a_m=1000

echo "Downsampling original LA to the complete LB grid..."

gmt grdedit unwrap_A.grd \
    -R${b_xmin}/${b_xmax}/${b_ymin}/${b_ymax} \
    -G_edit_A.grd

gmt grdsample _edit_A.grd \
    -R${b_xmin}/${b_xmax}/${b_ymin}/${b_ymax} \
    -I${b_xinc}/${b_yinc} -r -nn \
    -Gunwrap_A_onB_raw.grd
rm -f _edit_A.grd

full_b_rx="$(awk -v x1="$b_xmin" -v x2="$b_xmax" \
    -v d="$range_res" 'BEGIN {print (x2-x1)*d}')"
full_b_ry="$(awk -v y1="$b_ymin" -v y2="$b_ymax" \
    -v d="$azimuth_res" 'BEGIN {print (y2-y1)*d}')"

gmt grdedit unwrap_A_onB_raw.grd \
    -R0/$full_b_rx/0/$full_b_ry \
    -Gunwrap_A_onB_metric.grd

gmt grdfilter unwrap_A_onB_metric.grd \
    -D0 -Fg${prefilter_a_m} \
    -Gunwrap_A_onB_metric_filt.grd

gmt grdedit unwrap_A_onB_metric_filt.grd \
    -R${b_xmin}/${b_xmax}/${b_ymin}/${b_ymax} \
    -Gunwrap_A_onB.grd

# GMT 6.4 may slightly change the row count after filtering a metric-relabelled
# pixel grid.  Force the result back onto the exact native LB geometry.
gmt grdsample unwrap_A_onB.grd \
    -R${b_xmin}/${b_xmax}/${b_ymin}/${b_ymax} \
    -I${b_xinc}/${b_yinc} -rp -nn \
    -G_unwrap_A_onB_exact.grd
mv -f _unwrap_A_onB_exact.grd unwrap_A_onB.grd

rm -f unwrap_A_onB_raw.grd unwrap_A_onB_metric.grd \
    unwrap_A_onB_metric_filt.grd

echo "Complete-LB grid consistency:"
gmt grdinfo unwrap_A_onB.grd -C
gmt grdinfo unwrap_B.grd -C

# ---------------------------------------------------------------------------
# 2. Apply the original Gomba split-spectrum inversion at f_A.
# ---------------------------------------------------------------------------

scale_a="$(awk -v fa="$freq_a" -v fb="$freq_b" \
    'BEGIN {print fb/(fb*fb-fa*fa)}')"
gomba_factor="$(awk -v fa="$freq_a" -v fb="$freq_b" \
    'BEGIN {print fb*fb/(fb*fb-fa*fa)}')"

echo "Gomba scale       : $scale_a"
echo "Amplification     : $gomba_factor"

gmt grdmath unwrap_A_onB.grd "$freq_b" MUL = tmp1.grd
gmt grdmath unwrap_B.grd "$freq_a" MUL = tmp2.grd
gmt grdmath tmp1.grd tmp2.grd SUB "$scale_a" MUL \
    = iono_correction.grd
rm -f tmp1.grd tmp2.grd

read -r lb_work_xmin lb_work_xmax lb_work_ymin lb_work_ymax < <(
    gmt grdinfo iono_correction.grd -C |
        awk '{print $2, $3, $4, $5}'
)
orig_r_lb="${lb_work_xmin}/${lb_work_xmax}/${lb_work_ymin}/${lb_work_ymax}"

rx="$(awk -v x1="$lb_work_xmin" -v x2="$lb_work_xmax" \
    -v d="$range_res" 'BEGIN {print (x2-x1)*d}')"
ry="$(awk -v y1="$lb_work_ymin" -v y2="$lb_work_ymax" \
    -v d="$azimuth_res" 'BEGIN {print (y2-y1)*d}')"

gmt grdedit iono_correction.grd -R0/$rx/0/$ry \
    -Giono_correction_m.grd

# ---------------------------------------------------------------------------
# 3. Apply the coherence-based quality mask, exact nearest fill, and spatial
#    filtering.
# ---------------------------------------------------------------------------

echo "Preparing LA/LB coherence mask on the complete LB grid..."

gmt grdedit "$corr_a_src" \
    -R${b_xmin}/${b_xmax}/${b_ymin}/${b_ymax} \
    -G_corr_A_edit.grd
gmt grdsample _corr_A_edit.grd \
    -R${b_xmin}/${b_xmax}/${b_ymin}/${b_ymax} \
    -I${b_xinc}/${b_yinc} -r -nn \
    -Gcorr_A_onB.grd
rm -f _corr_A_edit.grd

# Apply the same exact-geometry safeguard to LA coherence.
gmt grdedit corr_A_onB.grd \
    -R${b_xmin}/${b_xmax}/${b_ymin}/${b_ymax} \
    -G_corr_A_relabel.grd
gmt grdsample _corr_A_relabel.grd \
    -R${b_xmin}/${b_xmax}/${b_ymin}/${b_ymax} \
    -I${b_xinc}/${b_yinc} -rp -nn \
    -G_corr_A_exact.grd
mv -f _corr_A_exact.grd corr_A_onB.grd
rm -f _corr_A_relabel.grd

gmt grdmath corr_A_onB.grd "$corr_b_src" ADD 2 DIV = corr_mean.grd
gmt grdmath corr_mean.grd "$coherence_threshold" GE \
    1 NaN IFELSE = corr_mask.grd
gmt grdmath iono_correction.grd corr_mask.grd MUL = iono_quality.grd

# Reject ionospheric estimates outside a frequency-dependent interval around
# the median.  For an f_A-referenced NISAR correction the applicable
# half-width is pi*f_A*f_B/(f_B^2-f_A^2).
iono_median="$(gmt grdinfo iono_quality.grd -C -L1 | awk '{print $12}')"
iono_limit="$(awk -v fa="$freq_a" -v fb="$freq_b" \
    'BEGIN {pi=atan2(0,-1); print pi*fa*fb/(fb*fb-fa*fa)}')"
iono_lower="$(awk -v m="$iono_median" -v l="$iono_limit" \
    'BEGIN {print m-l}')"
iono_upper="$(awk -v m="$iono_median" -v l="$iono_limit" \
    'BEGIN {print m+l}')"

echo "Ionosphere limits: median=$iono_median rad, +/-$iono_limit rad"

gmt grdmath iono_quality.grd "$iono_lower" GE \
    iono_quality.grd "$iono_upper" LE MUL \
    1 NaN IFELSE = outlier_mask.grd
gmt grdmath iono_quality.grd outlier_mask.grd MUL = _iono_quality_lb.grd

# Work in metric coordinates so filter_wavelength means the same physical
# distance in range and azimuth.
gmt grdedit _iono_quality_lb.grd -R0/$rx/0/$ry -Giono_quality_m.grd
rm -f _iono_quality_lb.grd

read -r metric_xinc metric_yinc < <(
    gmt grdinfo iono_quality_m.grd -C | awk '{print $8, $9}'
)
coarse_inc="$(awk -v w="$filter_wavelength" 'BEGIN {print w/8}')"

# 1 at rejected/empty pixels, 0 at quality-controlled observations.
gmt grdmath iono_quality_m.grd ISNAN = quality_nan_mask.grd

echo "Filling quality-mask gaps with nearest_grid_c_exact.py..."
"$python_cmd" "$nearest_python" iono_quality_m.grd filter_working.grd \
    --overwrite

spatial_filter_stage() {
    local input_grid="$1"
    local filter_type="$2"
    local output_grid="$3"

    gmt grdfilter "$input_grid" \
        -D0 "-F${filter_type}${filter_wavelength}/${filter_wavelength}" \
        -Ni -I${coarse_inc}/${coarse_inc} \
        -Gfilter_coarse.grd

    if [[ "$upsample_method" == "surface" ]]; then
        gmt grd2xyz filter_coarse.grd -s |
            gmt surface \
                -Riono_quality_m.grd \
                -I${metric_xinc}/${metric_yinc} -T0.1 \
                -G_filter_surface_gridline.grd

        read -r surface_nx surface_ny surface_reg < <(
            gmt grdinfo _filter_surface_gridline.grd -C |
                awk '{print $10, $11, $12}'
        )
        read -r target_nx target_ny target_reg < <(
            gmt grdinfo iono_quality_m.grd -C |
                awk '{print $10, $11, $12}'
        )
        if [[ "$surface_nx/$surface_ny/$surface_reg" == \
              "$target_nx/$target_ny/$target_reg" ]]; then
            mv -f _filter_surface_gridline.grd "$output_grid"
        else
            # Convert gridline output explicitly to the original pixel grid.
            gmt grdsample _filter_surface_gridline.grd \
                -Riono_quality_m.grd -nn -G"$output_grid"
            rm -f _filter_surface_gridline.grd
        fi
    else
        # Fast comparison mode.  The filtered coarse grid is already complete,
        # so direct interpolation is sufficient for evaluating the filter.
        gmt grdsample filter_coarse.grd \
            -Riono_quality_m.grd -nn -G"$output_grid"
        gmt grdcut "$output_grid" -Riono_quality_m.grd -N \
            -G_filter_fast_full.grd
        "$python_cmd" "$nearest_python" \
            _filter_fast_full.grd "$output_grid" --overwrite
        rm -f _filter_fast_full.grd
    fi
}

# Three robust iterations: median, boxcar, median.  Original
# quality-controlled pixels are retained between iterations; only rejected
# areas are updated from the smoothed field and then exactly nearest-filled.
for filter_type in m b m; do
    echo "Spatial ${filter_wavelength} m iteration: filter=$filter_type"
    spatial_filter_stage filter_working.grd "$filter_type" filter_stage.grd

    gmt grdmath iono_quality_m.grd 0 DENAN \
        1 quality_nan_mask.grd SUB MUL \
        filter_stage.grd quality_nan_mask.grd MUL ADD \
        = filter_mixed.grd

    "$python_cmd" "$nearest_python" filter_mixed.grd filter_working.grd \
        --overwrite
done

# Apply final boxcar and Gaussian smoothing.
echo "Final boxcar and Gaussian filters..."
spatial_filter_stage filter_working.grd b iono_boxcar.grd
spatial_filter_stage iono_boxcar.grd g iono_correction_filtered_LB_m.grd

# In fast comparison mode, use direct interpolation between iterations but
# retain the surface reconstruction for the final Gaussian coarse grid.
if [[ "$upsample_method" == "grdsample" ]]; then
    echo "Final surface reconstruction from Gaussian coarse grid..."
    gmt grd2xyz filter_coarse.grd -s |
        gmt surface \
            -Riono_quality_m.grd \
            -I${metric_xinc}/${metric_yinc} -T0.1 \
            -G_filter_final_surface.grd

    read -r final_nx final_ny final_reg < <(
        gmt grdinfo _filter_final_surface.grd -C |
            awk '{print $10, $11, $12}'
    )
    read -r target_nx target_ny target_reg < <(
        gmt grdinfo iono_quality_m.grd -C |
            awk '{print $10, $11, $12}'
    )
    if [[ "$final_nx/$final_ny/$final_reg" == \
          "$target_nx/$target_ny/$target_reg" ]]; then
        mv -f _filter_final_surface.grd iono_correction_filtered_LB_m.grd
    else
        gmt grdsample _filter_final_surface.grd \
            -Riono_quality_m.grd -nn -Giono_correction_filtered_LB_m.grd
        rm -f _filter_final_surface.grd
    fi
fi

# Keep the conventional filename used by the remaining run7 code.
gmt grdmath iono_correction_filtered_LB_m.grd 0 ADD = retrend_full_LB.grd

# ---------------------------------------------------------------------------
# 4. Convert the complete LB correction to the complete original LA grid.
# ---------------------------------------------------------------------------

echo "Resampling the filtered ionospheric correction to the LA grid..."

gmt grdedit retrend_full_LB.grd -R"$orig_r_lb" \
    -Giono_full_LB.grd

gmt grdedit iono_full_LB.grd \
    -R${a_xmin}/${a_xmax}/${a_ymin}/${a_ymax} \
    -G_iono_relabeled.grd
mv -f _iono_relabeled.grd iono_full_LB.grd

gmt grdsample iono_full_LB.grd \
    -R${a_xmin}/${a_xmax}/${a_ymin}/${a_ymax} \
    -I${a_xinc}/${a_yinc} -nn \
    -Giono_correction_filt.grd

# Force the exact LA footprint on GMT versions that trim one outer pixel
# during interpolation, then fill only those newly created border NaNs.
gmt grdcut iono_correction_filt.grd -Runwrap_A.grd -N \
    -G_iono_correction_full_la.grd
"$python_cmd" "$nearest_python" \
    _iono_correction_full_la.grd iono_correction_filt.grd --overwrite
rm -f _iono_correction_full_la.grd

# Restore the original valid-data footprint.
gmt grdmath unwrap_A.grd ISFINITE \
    iono_correction_filt.grd NaN IFELSE \
    = _iono_cf_tmp.grd
mv -f _iono_cf_tmp.grd iono_correction_filt.grd

gmt grdmath unwrap_A.grd iono_correction_filt.grd SUB \
    = unwrap_corrected.grd

# Optional geocoding.
trans_src="$la_dir/trans.dat"
if [[ -f "$trans_src" ]] && command -v proj_ra2ll.csh >/dev/null 2>&1; then
    ln -s "$trans_src" trans.dat
    if ! proj_ra2ll.csh trans.dat unwrap_corrected.grd \
        unwrap_corrected_ll.grd; then
        echo "WARNING: Geocoding failed; radar-grid output is valid."
        rm -f unwrap_corrected_ll.grd
    fi
fi

# ---------------------------------------------------------------------------
# 5. Write a compact numerical report.
# ---------------------------------------------------------------------------

grid_stat_line() {
    local label="$1"
    local grid="$2"
    gmt grdinfo "$grid" -C -L2 | awk -v label="$label" '
        {
            printf "%-29s %12.5g %12.5g %12.5g %12.5g %12.5g\n",
                label, $6, $7, $12, $13, $14
        }
    '
}

report="$work_dir/iono_correction_report.txt"
{
    echo "NISAR LA/LB ionospheric correction result"
    echo "=========================================="
    echo "Pair               : $pair_name"
    echo "Filter wavelength  : $filter_wavelength m"
    echo "Filter method      : median/boxcar/Gaussian"
    echo "Coherence threshold: $coherence_threshold"
    echo "Nearest fill       : nearest_grid_c_exact.py"
    echo "Coarse-grid rebuild: $upsample_method"
    echo "Gomba amplification: $gomba_factor"
    echo
    printf "%-29s %12s %12s %12s %12s %12s\n" \
        "grid" "minimum" "maximum" "mean" "std" "RMS"
    grid_stat_line "original LA before" unwrap_A.grd
    grid_stat_line "original LB before" unwrap_B.grd
    grid_stat_line "raw ionosphere" iono_correction.grd
    grid_stat_line "filtered ionosphere" iono_correction_filt.grd
    grid_stat_line "original LA after" unwrap_corrected.grd
} > "$report"

# ---------------------------------------------------------------------------
# 6. Automatically create unwrapped and wrapped 2x2 result figures.
# ---------------------------------------------------------------------------

robust_symmetric_limit() {
    gmt grdinfo "$@" -C -L2 | awk '
        {
            lo = $12 - 2 * $13
            hi = $12 + 2 * $13
            if (lo < 0) lo = -lo
            if (hi < 0) hi = -hi
            if (lo > lim) lim = lo
            if (hi > lim) lim = hi
        }
        END {
            if (!(lim > 0)) lim = 1
            printf "%.12g\n", lim
        }
    '
}

make_symmetric_cpt() {
    local limit="$1"
    local output_cpt="$2"
    local lower upper increment

    lower="$(awk -v x="$limit" 'BEGIN {printf "%.12g", -x}')"
    upper="$(awk -v x="$limit" 'BEGIN {printf "%.12g",  x}')"
    increment="$(awk -v x="$limit" 'BEGIN {printf "%.12g", 2*x/100}')"

    gmt makecpt -Cvik -T"${lower}/${upper}/${increment}" -Z \
        > "$output_cpt"
}

echo "Creating automatic unwrapped and wrapped 2x2 figures..."

plot_tmp="$(mktemp -d "${TMPDIR:-/tmp}/run7-iono-plot.XXXXXX")"
trap 'rm -rf "$plot_tmp"' EXIT

# LA, LB, and corrected LA share one robust zero-centered phase range.
# The ionospheric correction uses a separate robust zero-centered range.
phase_limit="$(robust_symmetric_limit \
    unwrap_A.grd unwrap_B.grd unwrap_corrected.grd)"
iono_limit="$(robust_symmetric_limit iono_correction_filt.grd)"

phase_cpt="$plot_tmp/phase.cpt"
iono_cpt="$plot_tmp/ionosphere.cpt"
wrapped_cpt="$plot_tmp/wrapped.cpt"

make_symmetric_cpt "$phase_limit" "$phase_cpt"
make_symmetric_cpt "$iono_limit" "$iono_cpt"

pi="3.141592653589793"
minus_pi="-3.141592653589793"
gmt makecpt \
    -Cmatlab/jet \
    -T"${minus_pi}/${pi}/0.062831853071796" \
    -Z > "$wrapped_cpt"

# 6.1 Unwrapped 2x2 figure.
unwrapped_base="$work_dir/iono_correction_2x2"

gmt begin "$unwrapped_base" png,pdf
    gmt set \
        FONT_TITLE 13p \
        FONT_LABEL 10p \
        FONT_ANNOT_PRIMARY 8p \
        MAP_TITLE_OFFSET 5p \
        MAP_FRAME_TYPE plain \
        COLOR_NAN 150/150/150

    gmt subplot begin 2x2 \
        -Fs12c/8c \
        -M0.35c/1.15c \
        -T"NISAR LA/LB ionospheric correction: $pair_name"

        gmt subplot set 0,0
        gmt grdimage unwrap_A.grd -C"$phase_cpt" -JX? \
            -Baf -BWSen+t"(a) LA before correction"
        gmt colorbar -C"$phase_cpt" \
            -DJBC+w8c/0.25c+h+o0/0.55c \
            -Baf+l"Phase (rad)"

        gmt subplot set 0,1
        gmt grdimage unwrap_B.grd -C"$phase_cpt" -JX? \
            -Baf -BWSen+t"(b) LB before correction"
        gmt colorbar -C"$phase_cpt" \
            -DJBC+w8c/0.25c+h+o0/0.55c \
            -Baf+l"Phase (rad)"

        gmt subplot set 1,0
        gmt grdimage iono_correction_filt.grd -C"$iono_cpt" -JX? \
            -Baf -BWSen+t"(c) Ionospheric correction"
        gmt colorbar -C"$iono_cpt" \
            -DJBC+w8c/0.25c+h+o0/0.55c \
            -Baf+l"Ionospheric phase (rad)"

        gmt subplot set 1,1
        gmt grdimage unwrap_corrected.grd -C"$phase_cpt" -JX? \
            -Baf -BWSen+t"(d) LA after correction"
        gmt colorbar -C"$phase_cpt" \
            -DJBC+w8c/0.25c+h+o0/0.55c \
            -Baf+l"Phase (rad)"

    gmt subplot end
gmt end

# 6.2 Wrap all four products to [-pi, pi].
phase_la_before="$work_dir/phase_LA_before.grd"
phase_lb_before="$work_dir/phase_LB_before.grd"
phase_iono="$work_dir/phase_iono_correction.grd"
phase_la_after="$work_dir/phase_LA_after.grd"

gmt grdmath unwrap_A.grd WRAP = "$phase_la_before"
gmt grdmath unwrap_B.grd WRAP = "$phase_lb_before"
gmt grdmath iono_correction_filt.grd WRAP = "$phase_iono"
gmt grdmath unwrap_corrected.grd WRAP = "$phase_la_after"

# 6.3 Wrapped matlab/jet 2x2 figure.
wrapped_base="$work_dir/iono_wrapped_phase_2x2"

gmt begin "$wrapped_base" png,pdf
    gmt set \
        FONT_TITLE 13p \
        FONT_LABEL 10p \
        FONT_ANNOT_PRIMARY 8p \
        MAP_TITLE_OFFSET 5p \
        MAP_FRAME_TYPE plain \
        COLOR_NAN 150/150/150

    gmt subplot begin 2x2 \
        -Fs12c/8c \
        -M0.35c/1.15c \
        -T"NISAR LA/LB wrapped phase: $pair_name"

        gmt subplot set 0,0
        gmt grdimage "$phase_la_before" -C"$wrapped_cpt" -JX? \
            -Baf -BWSen+t"(a) LA wrapped phase before correction"
        gmt colorbar -C"$wrapped_cpt" \
            -DJBC+w8c/0.25c+h+o0/0.55c \
            -Bxa3.14159265359+l"Wrapped phase (rad)"

        gmt subplot set 0,1
        gmt grdimage "$phase_lb_before" -C"$wrapped_cpt" -JX? \
            -Baf -BWSen+t"(b) LB wrapped phase before correction"
        gmt colorbar -C"$wrapped_cpt" \
            -DJBC+w8c/0.25c+h+o0/0.55c \
            -Bxa3.14159265359+l"Wrapped phase (rad)"

        gmt subplot set 1,0
        gmt grdimage "$phase_iono" -C"$wrapped_cpt" -JX? \
            -Baf -BWSen+t"(c) Wrapped ionospheric correction"
        gmt colorbar -C"$wrapped_cpt" \
            -DJBC+w8c/0.25c+h+o0/0.55c \
            -Bxa3.14159265359+l"Wrapped phase (rad)"

        gmt subplot set 1,1
        gmt grdimage "$phase_la_after" -C"$wrapped_cpt" -JX? \
            -Baf -BWSen+t"(d) LA wrapped phase after correction"
        gmt colorbar -C"$wrapped_cpt" \
            -DJBC+w8c/0.25c+h+o0/0.55c \
            -Bxa3.14159265359+l"Wrapped phase (rad)"

    gmt subplot end
gmt end

# Remove temporary products but retain quality/filter diagnostics.
rm -f filter_coarse.grd filter_stage.grd filter_mixed.grd \
    iono_correction_m.grd iono_full_LB.grd

echo
echo "============================================================"
echo "Ionospheric correction completed."
echo "Output directory:"
echo "  $work_dir"
echo
echo "Main outputs:"
echo "  iono_correction.grd       raw correction on complete LB grid"
echo "  iono_correction_filt.grd  filtered correction on original LA grid"
echo "  iono_correction_filtered_LB_m.grd"
echo "                               20 km correction on metric LB grid"
echo "  corr_mean.grd             mean LA/LB coherence on LB grid"
echo "  iono_quality.grd          coherence-screened raw correction"
echo "  unwrap_corrected.grd      corrected original LA phase"
echo "  unwrap_corrected_ll.grd   corrected geographic phase (if available)"
echo "  iono_correction_report.txt"
echo "  iono_correction_2x2.png/.pdf"
echo "  iono_wrapped_phase_2x2.png/.pdf"
echo "  phase_LA_before.grd"
echo "  phase_LB_before.grd"
echo "  phase_iono_correction.grd"
echo "  phase_LA_after.grd"
echo "============================================================"
echo
cat "$report"
